export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const TOGGLE_NETWORK = 'TOGGLE_NETWORK';
export const TOGGLE_POOL = 'TOGGLE_POOL';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';

export const SET_WALLET_BALANCE = 'SET_WALLET_BALANCE';
export const SET_MONITOR_WALLET = 'SET_MONITOR_WALLET';

export const GAS_PRICE_REQUEST = 'GAS_PRICE_REQUEST';
export const GAS_PRICE_SUCCESS = 'GAS_PRICE_SUCCESS';
export const GAS_PRICE_FAILED = 'GAS_PRICE_FAILED';

export const PORTFOLIO_BALANCE_REQUEST = 'PORTFOLIO_BALANCE_REQUEST';
export const PORTFOLIO_BALANCE_SUCCESS = 'PORTFOLIO_BALANCE_SUCCESS';
export const PORTFOLIO_BALANCE_FAILED = 'PORTFOLIO_BALANCE_FAILED';

export const WHALE_TX_REQUEST = 'WHALE_TX_REQUEST';
export const WHALE_TX_SUCCESS = 'WHALE_TX_SUCCESS';
export const WHALE_TX_FAILED = 'WHALE_TX_FAILED';

export const NFT_DETAILS_REQUEST = 'NFT_DETAILS_REQUEST';
export const NFT_DETAILS_SUCCESS = 'NFT_DETAILS_SUCCESS';
export const NFT_DETAILS_FAILED = 'NFT_DETAILS_FAILED';

export const POOL_DETAILS_REQUEST = 'POOL_DETAILS_REQUEST';
export const POOL_DETAILS_SUCCESS = 'POOL_DETAILS_SUCCESS';
export const POOL_DETAILS_FAILED = 'POOL_DETAILS_FAILED';
